[params]
    keywords = "Schriftmuster, Schriften, Papier, BÃ¼cher, fonts, paper, books"
    copyrightYears = "MMXXI - MMXXVI"
    stylesheets = []
    cc = true
    productionIIIFURLPrefix="https://static.projektemacher.org/schriftmuster/"
    disableScale = true
    description = "Specimens of old typefaces from catalogues for printers and from documents"
    wikidata = true
    debug = false

    [params.preview]
        outputPrefix = "ogPreview"
        outputSuffix = ".jpg"
        format =  "svg"
        image = "preview.png"
        source = "file"
        [params.preview.size]
            height = 630
            width = 1200
        [params.preview.svg]
            template = "./Source Files/Other/preview-template.svg"
            removeMissing = true

[params.author]
  email = 'mail@christianmahnke.de'
  name = 'Christian Mahnke'
  uri = 'http://www.wikidata.org/entity/Q137668638'
